INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (1, 'Single House');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (2, 'Attached House');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (3, 'Town House');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (4, 'Appartment');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (5, 'Store');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (6, 'Farm');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (7, 'Factory');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (8, 'Mall');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (9, 'Building');
INSERT INTO myapp_propertycategory (propertyCategory, propertyCategoryName) VALUES (10, 'Other');