INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (1, 1, 'add_logentry', 'Can add log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (2, 1, 'change_logentry', 'Can change log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (3, 1, 'delete_logentry', 'Can delete log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (4, 1, 'view_logentry', 'Can view log entry');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (5, 2, 'add_permission', 'Can add permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (6, 2, 'change_permission', 'Can change permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (7, 2, 'delete_permission', 'Can delete permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (8, 2, 'view_permission', 'Can view permission');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (9, 3, 'add_group', 'Can add group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (10, 3, 'change_group', 'Can change group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (11, 3, 'delete_group', 'Can delete group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (12, 3, 'view_group', 'Can view group');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (13, 4, 'add_user', 'Can add user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (14, 4, 'change_user', 'Can change user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (15, 4, 'delete_user', 'Can delete user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (16, 4, 'view_user', 'Can view user');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (17, 5, 'add_contenttype', 'Can add content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (18, 5, 'change_contenttype', 'Can change content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (19, 5, 'delete_contenttype', 'Can delete content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (20, 5, 'view_contenttype', 'Can view content type');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (21, 6, 'add_session', 'Can add session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (22, 6, 'change_session', 'Can change session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (23, 6, 'delete_session', 'Can delete session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (24, 6, 'view_session', 'Can view session');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (25, 7, 'add_city', 'Can add city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (26, 7, 'change_city', 'Can change city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (27, 7, 'delete_city', 'Can delete city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (28, 7, 'view_city', 'Can view city');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (29, 8, 'add_country', 'Can add country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (30, 8, 'change_country', 'Can change country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (31, 8, 'delete_country', 'Can delete country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (32, 8, 'view_country', 'Can view country');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (33, 9, 'add_property', 'Can add property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (34, 9, 'change_property', 'Can change property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (35, 9, 'delete_property', 'Can delete property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (36, 9, 'view_property', 'Can view property');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (37, 10, 'add_property_facing', 'Can add property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (38, 10, 'change_property_facing', 'Can change property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (39, 10, 'delete_property_facing', 'Can delete property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (40, 10, 'view_property_facing', 'Can view property_ facing');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (41, 11, 'add_property_sector', 'Can add property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (42, 11, 'change_property_sector', 'Can change property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (43, 11, 'delete_property_sector', 'Can delete property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (44, 11, 'view_property_sector', 'Can view property_ sector');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (45, 12, 'add_propertycategory', 'Can add property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (46, 12, 'change_propertycategory', 'Can change property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (47, 12, 'delete_propertycategory', 'Can delete property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (48, 12, 'view_propertycategory', 'Can view property category');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (49, 13, 'add_propertyimages', 'Can add property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (50, 13, 'change_propertyimages', 'Can change property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (51, 13, 'delete_propertyimages', 'Can delete property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (52, 13, 'view_propertyimages', 'Can view property images');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (53, 14, 'add_province', 'Can add province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (54, 14, 'change_province', 'Can change province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (55, 14, 'delete_province', 'Can delete province');
INSERT INTO auth_permission (id, content_type_id, codename, name) VALUES (56, 14, 'view_province', 'Can view province');