# Generated by Django 2.1.2 on 2018-11-12 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('roleCode_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RoleCode')),
                ('rolePermission_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RolePermission')),
            ],
        ),
    ]
