# Generated by Django 2.1.2 on 2018-11-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rolepermissiondetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermissionTyoe',
            new_name='PermissionType',
        ),
        migrations.RenameField(
            model_name='rolepermissiondetail',
            old_name='id',
            new_name='rolePermissionDetail_ID',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='roleCode_ID',
        ),
    ]
