# Generated by Django 2.1.2 on 2018-11-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181112_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users'),
        ),
    ]
